#!/bin/bash

# RAGFlow MVP - One-Command Startup Script
# This script starts the entire RAGFlow MVP system with full automation

set -e

echo "🚀 Starting RAGFlow MVP - Email Intelligence System for IVC"
echo "========================================================"

# Check if Docker and Docker Compose are installed
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed. Please install Docker first."
    exit 1
fi

if ! command -v docker-compose &> /dev/null; then
    echo "❌ Docker Compose is not installed. Please install Docker Compose first."
    exit 1
fi

# Create necessary directories
echo "📁 Creating necessary directories..."
mkdir -p config
mkdir -p backend/data
mkdir -p backend/logs

# Check if .env file exists, create a basic one if not
if [ ! -f .env ]; then
    echo "📝 Creating basic .env file..."
    cat > .env << EOF
# RAGFlow MVP Environment Configuration
# Auto-generated by start.sh

# Database
POSTGRES_DB=ragflow_db
POSTGRES_USER=ragflow
POSTGRES_PASSWORD=ragflow123

# Google OAuth (IVC Company)
GOOGLE_CLIENT_ID=792999098406-hmolqmci0o9op9t2vpknmhespml53bau.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
GOOGLE_PROJECT_ID=ivc-ragflow-project

# Google Drive Folders
GDRIVE_DOCUMENTS_FOLDER_ID=1oas1TEtW26ZNvW2jekk6Y8R2Hb85IUmn
GDRIVE_ATTACHMENTS_FOLDER_ID=1dEjEogfE3WlHypaY8vuaWiBeZjjuVTGV

# LLM Configuration
LLM_MODEL=mistral:7b-instral-v0.3-q4_K_M
LLM_TEMPERATURE=0.3

# System
LOG_LEVEL=INFO
OCR_ENABLED=true
MAX_CONCURRENT_PROCESSES=4

# Security (CHANGE THESE IN PRODUCTION!)
SECRET_KEY=ragflow-secret-key-change-in-production
TOKEN_ENCRYPTION_KEY=ragflow-encryption-key-32-chars-123
EOF
    echo "✅ Created .env file with default configuration"
fi

# Stop any existing containers
echo "🛑 Stopping any existing RAGFlow containers..."
docker-compose down --remove-orphans || true

# Clean up any orphaned containers
echo "🧹 Cleaning up orphaned containers..."
docker container prune -f || true

# Pull latest images
echo "📥 Pulling latest Docker images..."
docker-compose pull

# Build custom images
echo "🔨 Building custom Docker images..."
docker-compose build

# Start the system with initialization
echo "🚀 Starting RAGFlow MVP system..."
docker-compose up -d

# Wait for initialization to complete
echo "⏳ Waiting for system initialization..."
echo "This may take 5-10 minutes for the first run (downloading models, setting up database)..."

# Monitor the init container
docker-compose logs -f init &
LOGS_PID=$!

# Wait for init container to complete
while [ "$(docker-compose ps -q init)" ]; do
    sleep 10
done

# Stop the logs monitoring
kill $LOGS_PID 2>/dev/null || true

# Show final status
echo ""
echo "🎉 RAGFlow MVP System Status"
echo "========================="

# Check service health
services=("postgres" "redis" "ragflow" "ollama" "backend" "frontend")
all_healthy=true

for service in "${services[@]}"; do
    if docker-compose ps | grep -q "${service}.*Up.*healthy"; then
        echo "✅ $service: Running and Healthy"
    elif docker-compose ps | grep -q "${service}.*Up"; then
        echo "⚠️  $service: Running (health check pending)"
    else
        echo "❌ $service: Not Running"
        all_healthy=false
    fi
done

echo ""
if [ "$all_healthy" = true ]; then
    echo "🎊 SUCCESS! Your RAGFlow MVP is ready to go!"
    echo ""
    echo "📱 Access your system:"
    echo "   🌐 Frontend (Web UI):     http://localhost:3000"
    echo "   🔧 Backend API:           http://localhost:8000"
    echo "   📊 RAGFlow:               http://localhost:9380"
    echo "   🤖 Ollama:                http://localhost:11434"
    echo "   🗄️  PostgreSQL:           localhost:5432"
    echo "   📦 Redis:                 localhost:6379"
    echo ""
    echo "🎯 Quick Start:"
    echo "   1. Open http://localhost:3000 in your browser"
    echo "   2. Go to the Authentication tab 🔐"
    echo "   3. The first Gmail (storesnproduction@ivc-valves.com) should auto-authenticate"
    echo "   4. Use 'Auto-Authenticate All' for other Gmail accounts"
    echo "   5. Start processing emails and enjoy your AI email intelligence!"
    echo ""
    echo "📧 Configured Email Sequence:"
    echo "   1. storesnproduction@ivc-valves.com (auto-auth)"
    echo "   2. hr.ivcvalves@gmail.com"
    echo "   3. umesh.jadhav@ivc-valves.com"
    echo "   4. arpatil@ivc-valves.com"
    echo "   5. exports@ivc-valves.com"
    echo "   6. sumit.basu@ivc-valves.com"
    echo "   7. hr@ivc-valves.com"
    echo ""
else
    echo "⚠️  Some services are not healthy. Check the logs with:"
    echo "   docker-compose logs [service-name]"
    echo ""
    echo "🔧 Troubleshooting commands:"
    echo "   docker-compose ps              # Check service status"
    echo "   docker-compose logs backend    # Check backend logs"
    echo "   docker-compose logs ollama     # Check Ollama logs"
    echo "   docker-compose restart         # Restart all services"
fi

echo ""
echo "🛠️  Management Commands:"
echo "   docker-compose logs -f         # View live logs"
echo "   docker-compose stop            # Stop all services"
echo "   docker-compose restart         # Restart all services"
echo "   docker-compose down            # Stop and remove containers"
echo "   ./start.sh                     # Run this script again"
echo ""
echo "📖 For detailed documentation, see: SYSTEM_OVERVIEW.md"
echo "🆘 For support, check the logs and troubleshooting guide" 